org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.8
minecraft_version_range=[1.21.7, 1.21.9)
neoforge_version=21.8.54
geckolib_version=5.2.1

mod_version=2.1.7+mc1.21.8-1.21.7-backport
maven_group=com.neutrinodust
archives_base_name=useful_ores-neoforge
