org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.3
minecraft_version_range=[1.21.3, 1.21.4)
neoforge_version=21.3.97
geckolib_version=4.7.+

mod_version=2.1.7+mc1.21.3-backport-v91
maven_group=com.neutrinodust
archives_base_name=useful_ores-neoforge
