modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "MIT LICENSE" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "useful_ores" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Useful Ores" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile="useful_ores.png" #optional
credits="" #optional
authors = "NeutrinoDust" #optional
description = '''Adds 14 ores and recipes (Swords, Armors, Tools and Blocks)''' #mandatory (Supports multiline text)
[[mixins]]
config = "useful_ores.mixins.json"
[[mixins]]
config = "useful_ores.neoforge.mixins.json"
[[mixins]]
config = "useful_ores.sound.mixins.json"
[[dependencies.useful_ores]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.11.44,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.useful_ores]]
modId = "geckolib"
type = "required"
versionRange = "[5.4.0,5.5.0)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.useful_ores]]
modId = "sodium"
type = "optional"
versionRange = "[0.8.0,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.useful_ores]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21.11, 1.21.12)"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.useful_ores]
#openGLVersion="[3.2,)"
